display: top
links:
  - name: ä¸ªäººä¸»é¡µ
    link: https://ixk.me
    avatar: /image/config/friends/links/0/avatar.400x400.png
    author: Otstar Lin
    description: Otstar's Spaceçš„æºç ï¼Œä¸ªäººä¸»é¡µã€‚
  - name: é’ç©ºä¹‹è“
    link: https://blog.ixk.me
    avatar: /image/config/friends/links/1/avatar.400x400.png
    author: Otstar Lin
    description: ç«™åœ¨æ—¶å…‰ä¸€ç«¯ï¼Œå›å¿†è¿‡å¾€è®°å¿†ã€‚
  - name: GitHub
    link: https://github.com/syfxlin
    avatar: /image/config/friends/links/2/avatar.400x400.png
    author: Otstar Lin
    description: >-
      ğŸ’»Coding / ğŸ‰GuGuGu / ğŸ“– Learning / ğŸš© Open Source developer / ğŸ› Bug
      making machine
lost_links: []
