display: none
categories:
  - name: Focus
    projects:
      - name: Depker
        link: https://github.com/syfxlin/depker
        description: >-
          A deployment tool based on Docker, designed to lower the difficulty of
          automating application deployment for low-performance self-hosted
          servers, and provide continuous deployment capabilities.
        components:
          - simple-icons:deno
          - simple-icons:typescript
          - simple-icons:docker
          - ri:server-line
  - name: Frameworks
    projects:
      - name: XKJava
        link: https://github.com/syfxlin/xkjava
        description: A Lightweight Spring-like Java Framework
        components:
          - simple-icons:spring
          - la:java
      - name: XK-Server
        link: https://github.com/syfxlin/xkserver
        description: A lightweight Java web server, not finished.
        components:
          - la:java
      - name: XK-PHP
        link: https://github.com/syfxlin/xkphp
        description: A Lightweight Laravel-like PHP Framework
        components:
          - simple-icons:laravel
          - simple-icons:php
  - name: Tools / Utility Libraries
    projects:
      - name: Reve
        link: https://github.com/syfxlin/reve
        description: >-
          Reve is a library of enhancements to vanilla-extract to improve the
          experience of using vanilla-extract and reduce unnecessary time
          consumption due to specific programming paradigms.
        components:
          - simple-icons:typescript
          - simple-icons:css3
          - simple-icons:styledcomponents
      - name: Reks
        link: https://github.com/syfxlin/reks
        description: >-
          Reks is a library of enhancements to reks to improve the experience of
          using keystatic.
        components:
          - simple-icons:typescript
      - name: Ustyled
        link: https://github.com/syfxlin/ustyled
        description: A CSS-in-JS utility library based on Emotion.js.
        components:
          - simple-icons:typescript
          - simple-icons:css3
          - simple-icons:styledcomponents
  - name: Note System / WYSIWYG Editor
    projects:
      - name: Hoshi Note (Service)
        link: https://github.com/syfxlin/hoshi-note
        description: >-
          Hoshi-Note is a cloud note system, based on Spring Boot and Spring
          Cloud development, using microservices and distributed model
          deployment.
        components:
          - simple-icons:spring
          - la:java
          - simple-icons:kubernetes
          - simple-icons:redis
          - simple-icons:cockroachlabs
          - simple-icons:rabbitmq
          - simple-icons:minio
          - simple-icons:nginx
      - name: Hoshi Note (UI)
        link: https://github.com/syfxlin/hoshi-ui
        description: >-
          Hoshi-Note is a cloud note system, based on Spring Boot and Spring
          Cloud development, using microservices and distributed model
          deployment.
        components:
          - simple-icons:react
          - simple-icons:typescript
          - simple-icons:vite
      - name: Tiptap Starter Kit
        link: https://github.com/syfxlin/tiptap-starter-kit
        description: >-
          An unofficial suite of Tiptap editors with a collection of common
          extensions.
        components:
          - simple-icons:typescript
          - simple-icons:css3
      - name: XK-Editor Next
        link: https://github.com/syfxlin/xkeditor-next
        description: An editor with rich text support, based on Rich Markdown Editor.
        components:
          - simple-icons:react
          - simple-icons:typescript
          - simple-icons:markdown
      - name: XK-Note
        link: https://github.com/syfxlin/xknote
        description: A cloud notebook with all sorts of amazing features.
        components:
          - simple-icons:laravel
          - simple-icons:php
          - simple-icons:vuedotjs
          - simple-icons:javascript
          - simple-icons:markdown
      - name: XK-Editor
        link: https://github.com/syfxlin/xkeditor
        description: An editor with rich text and Markdown support.
        components:
          - simple-icons:vuedotjs
          - simple-icons:javascript
          - simple-icons:markdown
  - name: Websites
    projects:
      - name: Home
        link: https://github.com/syfxlin/home
        description: Source code for Otstar's Space, personal home page.
        components:
          - simple-icons:nextdotjs
          - simple-icons:typescript
      - name: Blog
        link: https://github.com/syfxlin/blog
        description: >-
          Otstar Lin's personal blog repository / Next.js / React / TypeScript /
          Keystatic CMS
        components:
          - simple-icons:nextdotjs
          - simple-icons:typescript
  - name: Contributed
    projects:
      - name: vanilla-extract
        link: https://github.com/vanilla-extract-css/vanilla-extract
        description: >-
          Zero-runtime Stylesheets-in-TypeScript. Write your styles in
          TypeScript (or JavaScript) with locally scoped class names and CSS
          Variables, then generate static CSS files at build time.
        components:
          - simple-icons:typescript
          - simple-icons:css3
          - simple-icons:webpack
      - name: Artalk
        link: https://github.com/ArtalkJS/Artalk
        description: Your self-hosted comment system.
        components:
          - simple-icons:typescript
          - simple-icons:go
      - name: RSSHub
        link: https://github.com/DIYgod/RSSHub
        description: >-
          RSSHub is an open source, easy to use, and extensible RSS feed
          generator. It's capable of generating RSS feeds from pretty much
          everything.
        components:
          - ri:rss-line
          - simple-icons:javascript
  - name: Gatsby Ecosystem
    projects:
      - name: Coline Theme for Gatsby
        link: https://github.com/syfxlin/gatsby-theme-coline
        description: A Gatsby theme for publishing articles to your website.
        components:
          - simple-icons:gatsby
          - simple-icons:typescript
          - simple-icons:mdx
          - simple-icons:decapcms
      - name: Express Server for Gatsby
        link: https://github.com/syfxlin/gatsby-plugin-express
        description: >-
          Gives you a way to integrate your Gatsby site with the Node.js server
          using Express
        components:
          - simple-icons:gatsby
          - simple-icons:express
          - simple-icons:typescript
      - name: Directus Source for Gatsby
        link: https://github.com/syfxlin/gatsby-source-directus
        description: The unofficial Gatsby source plugin for Directus CMS projects.
        components:
          - simple-icons:gatsby
          - simple-icons:typescript
  - name: WordPress Ecosystem
    projects:
      - name: Origami
        link: https://github.com/syfxlin/origami
        description: A WordPress theme with many powerful features, clean, light and fast.
        components:
          - simple-icons:wordpress
          - simple-icons:php
          - simple-icons:javascript
      - name: Origami to Hexo Converter
        link: https://github.com/syfxlin/origami-wp-hexo
        description: >-
          Origami wp hexo is a WordPress to Hexo conversion solution for
          Origami!
        components:
          - simple-icons:wordpress
          - simple-icons:hexo
      - name: Hermit-X Blocks
        link: https://github.com/syfxlin/hermit-x-blocks
        description: Gutenberg blocks for Hermit-X Music WordPress Plugin.
        components:
          - simple-icons:wordpress
          - simple-icons:javascript
      - name: Toast for WordPress
        link: https://github.com/syfxlin/toast-for-wp
        description: Toastr.js WordPress Plugin
        components:
          - simple-icons:wordpress
          - simple-icons:javascript
  - name: Toys
    projects:
      - name: Graffit Board
        link: https://github.com/syfxlin/graffiti-board
        description: A simple Canvas or SVG-based graffiti board.
        components:
          - simple-icons:javascript
          - simple-icons:svg
      - name: Docset Generator
        link: https://github.com/syfxlin/docset-generator
        description: Dash Document Generator.
        components:
          - simple-icons:javascript
          - simple-icons:nodedotjs
      - name: VSCode Acrylic Plugin
        link: https://github.com/syfxlin/vscode-acrylic
        description: >-
          Add Acrylic,BlurBehind,TransparentGradient background effects to
          VSCode(Windows).
        components:
          - simple-icons:visualstudiocode
      - name: Spring Learn Monorepo
        link: https://github.com/syfxlin/spring-learn
        description: My code repository for learning Spring.
        components:
          - simple-icons:spring
          - la:java
      - name: Useless Code
        link: https://github.com/syfxlin/code
        description: The place where I keep my useless code.
        components:
          - la:java
          - simple-icons:php
      - name: Obsidian Prettier
        link: https://github.com/syfxlin/obsidian-prettier
        description: Plugin for formatting Obsidian documents using Prettier
        components:
          - simple-icons:obsidian
          - simple-icons:javascript
      - name: Obsidian Autolinker
        link: https://github.com/syfxlin/obsidian-autolinker
        description: >-
          Plugin to automatically add bi-directional links to Obsidian
          documents.
        components:
          - simple-icons:obsidian
          - simple-icons:javascript
